### ISSUE TITLE
Add a flag for only syncing the latest version of each chart

### ISSUE THREAD

**Issue by tompizmor** [bitnami-labs/charts-syncer#107]
Currently, chart-syncer is syncing all the charts of the registry unless we specify the --from-date flag. 
This might cause different issues: old charts with issues won’t be synced showing errors, limitations on the number of requests to the registry, time and size taken by the sync process, etc. For solving the current issue and potential ones in the future we will create a flag for allowing users to only sync the latest version of each chart.

**Comment by migmartri** [comment]
Already implemented https://github.com/bitnami-labs/charts-syncer/pull/128
