### ISSUE TITLE
Sync chart failed of target repo type is chartmuseum

### ISSUE THREAD

**Issue by yidaqiang** [bitnami-labs/charts-syncer#173]
When I sync chart from chartmuseum to chartmuseum, Problems encountered.

log is：
```txt
Using config file: "config.yaml"
There are no charts out of sync!
```
I found the place where the bug occurred

https://github.com/bitnami-labs/charts-syncer/blob/6d18fc98aab230beb0aa7870b36412ee971923ba/pkg/client/repo/chartmuseum/chartmuseum.go#L59

```go
// GetUploadURL returns the URL to upload a chart
func (r *Repo) GetUploadURL() string {
	u := *r.url
	u.Path = "/api/charts"
	return u.String()
}
```
Target repo url is  https://chart.exmaple.com/myrepo, After execution `u.Path = "/api/charts"`, u.Path is `/api/charts`, Not expected `/myrepo/api/charts`

So The correct code is
```
// GetUploadURL returns the URL to upload a chart
func (r *Repo) GetUploadURL() string {
	u := *r.url
	u.Path += "/api/charts"
	return u.String()
}
```

Is this appropriate, Do I need to create PR ?

**Comment by jiparis** [comment]
Hi @yidaqiang, thanks for reporting the issue. 
According to Chartmuseum docs, Charts API is exposed under `/api/charts`. Do you have your deployment behind a proxy or virtual host? In that case, it would make sense to prepend the virtual host name, not the whole URL.

Can you post here the relevant part of your `config.yaml` file?

**Comment by yidaqiang** [comment]
In Chartmuseum [docs](https://chartmuseum.com/docs/), Here is a sample command：

```bash
curl --data-binary "@mychart-0.1.0.tgz" http://localhost:8080/api/charts
```
But in fact, The following commands are used

```bash
curl -u username:password --data-binary "@mychart-0.1.0.tgz" http://localhost:8080/mysql-repo/api/charts
# or 
curl -u username:password --data-binary "@mychart-0.1.0.tgz" http://localhost:8080/api/mysql-repo/charts
```
Only use `/api/charts` without `myrepo`, chartmuseum returen `{ "error": "not found" }`

See the link below for detailed logic

https://github.com/helm/chartmuseum/blob/a3629ef8521b1c6149c885482a87272f9b8c6b78/pkg/chartmuseum/router/match.go#L128

**Comment by jiparis** [comment]
Hi @yidaqiang, sorry for the late response.
Yes, you are right, it looks like your approach would fix the issue. Can you please create a PR for the team to review?

Thank you for your contribution!
