### ISSUE TITLE
Charts versions

### ISSUE THREAD

**Issue by gadido30** [bitnami-labs/charts-syncer#205]
Dose chart sync v2  support charts version?
like "helm pull stable/mysql --version 1.6.1"

**Comment by beltran-rubo** [comment]
Charts-syncer is a tool for syncing multiple Helm charts and keep the source and the target registry in sync. For that use case, we would recommend to use the distribution tooling for Helm https://github.com/vmware-labs/distribution-tooling-for-helm that is the component that Charts-syncer use behind scenes.

This tool allows you to pull a Helm chart with all the images locally, creating a 'wrap' easy to move to any other registry. Would that work for your use case?

**Comment by gadido30** [comment]
@beltran-rubo Thank you
