### ISSUE TITLE
pre-v2 behaviour

### ISSUE THREAD

**Issue by TheMeier** [bitnami-labs/charts-syncer#210]
To me it looks like it is not possible with v2 do disable the image-download and chart-rewriting. Am I missing something? Is the use-case where a chart is simple copied "as is" in scope of this tool?

**Comment by alemorcuq** [comment]
> Is the use-case where a chart is simple copied "as is" in scope of this tool?

No, it's not. For that use case, Harbor provides a feature to copy charts between repositories. Alternatively, you can use crane to copy your charts.

**Comment by TheMeier** [comment]
Thanks for the clarification
