### ISSUE TITLE
Manage dependencies specified using a Chart.yaml file

### ISSUE THREAD

**Issue by tompizmor** [bitnami-labs/charts-syncer#28]
The tool only knows how to manage the dependencies if they are specified in a *requirements.yaml* file.

Since Helm3 it is recommended to specify the dependencies using the Chart.yaml and a new Chart.lock instead of the requirements.yaml and requirements.lock used in Helm2

The reason to first focus on requirements.yaml instead of Chart.yaml is that all Bitnami charts still uses the helm2 approach to manage the dependencies. (As it is also compatible with Helm 3)

**Comment by jotadrilo** [comment]
@tompizmor can this issue considered done?

**Comment by jotadrilo** [comment]
We confirmed that this is done!
