### ISSUE TITLE
Perform retries when pulling/pushing charts if there are connectivity issues

### ISSUE THREAD

**Issue by fjagugar** [bitnami-labs/charts-syncer#89]
If there are intermittent networking issues when using the syncer, any pull or push of the chart will fail, forcing the user to re-run the whole sync process. If the issue pulling/pushing the chart is related to connectivity issues, we should retry some times in case the error is transient.

**Comment by jotadrilo** [comment]
I don't think this is a problem. The retry mechanism should be implemented by the user, not this tool.

**Comment by jotadrilo** [comment]
That said, the tool creates a filesystem cache that will speed up consecutive runs.
